const shoppeItems = {
  book: [
    {
      name: "Comedy Gold",
      type: "book",
      price: "$419.99",
      level: "Novice",
      rating: "5",
      releaseDate: "1999",
      description: "Lorem Ipsum",
      image: "",
    },
    {
      name: "Enchanted Book",
      type: "book",
      price: "$31.99",
      level: "Intermediate",
      rating: "3",
      releaseDate: "1999",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/books/comedy_gold.jpg",
    },
    {
      name: "[REDACTED]",
      type: "book",
      price: "$899.99",
      level: "Expert",
      rating: "0",
      releaseDate: "69",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/books/enchanted_book.jpg",
    },
    {
      name: "Do-It-Yourself",
      type: "book",
      price: "$229.99",
      level: "Intermediate",
      rating: "5",
      releaseDate: "2003",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/books/hvac_wizzard.jpg",
    },
    {
      name: "Love Story",
      type: "book",
      price: "$14.99",
      level: "Advanced",
      rating: "1",
      releaseDate: "2018",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/books/love_book.jpg",
    },
    {
      name: "Free Book",
      type: "book",
      price: "$1299.99",
      level: "Expert",
      rating: "5",
      releaseDate: "2999",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/books/most_expensive_book_we_have.jpg",
    },
    {
      name: "VVizard of Oz",
      type: "book",
      price: "$9.99",
      level: "Novice",
      rating: "2",
      releaseDate: "1933",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/books/oz.jpg",
    },
    {
      name: "Spell Book",
      type: "book",
      price: "$29.99",
      level: "Novice",
      rating: "5",
      releaseDate: "1999",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/books/spell_book.jpg",
    },
  ],
  minions: [
    {
      name: 'Real "Owl"',
      type: "minion",
      price: "$9.99",
      level: "novice",
      rating: "3",
      releaseDate: "2023",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/minions/def_a_real_owl.jpg",
    },
    {
      name: "Good Boi",
      type: "minion",
      price: "$99.99",
      level: "Intermediate",
      rating: "4",
      releaseDate: "2022",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/minions/good_boi.jpg",
    },
    {
      name: "The Bestest Boi",
      type: "minion",
      price: "$867530.99",
      level: "Expert",
      rating: "6",
      releaseDate: "2023",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/minions/teddy.jpg",
    },
    {
      name: "Homer",
      type: "minion",
      price: "$44.99",
      level: "Advanced",
      rating: "3",
      releaseDate: "2001",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/minions/homer.jpg",
    },
    {
      name: "Minion",
      type: "minion",
      price: "$9.99",
      level: "Novice",
      rating: "3",
      releaseDate: "2023",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/minions/minion-minion.jpg",
    },
    {
      name: "Perry the Platypus",
      type: "minion",
      price: "$9.99",
      level: "Novice",
      rating: "3",
      releaseDate: "2023",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/minions/perry_da_p.jpg",
    },
    {
      name: "Radical Condor",
      type: "minion",
      price: "$9.99",
      level: "Novice",
      rating: "3",
      releaseDate: "2023",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/minions/radical_condor.jpg",
    },
    {
      name: "Doug",
      type: "minion",
      price: "Priceless",
      level: "Expert",
      rating: "6",
      releaseDate: "2023",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/minions/doug.jpg",
    },
  ],
  vestments: [
    {
      name: "Bed Sheet",
      type: "vestments",
      price: "$9.99",
      level: "Novice",
      rating: "3",
      releaseDate: "680",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/robes/bed_sheet_ghost_wizard_robe.jpg",
    },
    {
      name: "Blue Satin",
      type: "vestments",
      price: "$39.99",
      level: "Intermediate",
      rating: "4",
      releaseDate: "920",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/robes/blue_satin_robe.jpg",
    },
    {
      name: "Shadow Shroud",
      type: "vestments",
      price: "$99.99",
      level: "Advanced",
      rating: "5",
      releaseDate: "714",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/robes/dark_wizard_robe.jpg",
    },
    {
      name: "Vestment of Side Effects",
      type: "vestments",
      price: "$119.99",
      level: "Intermediate",
      rating: "3",
      releaseDate: "1987",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image:
        "../images/robes/wizard_robe_that_makes_you_bald_and_maybe_a_monk.jpg",
    },
    {
      name: "Golden Vestment Staff Combo",
      type: "vestments",
      price: "$1199.99",
      level: "Expert",
      rating: "4",
      releaseDate: "001",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/robes/wealthy_wizard_robe.jpg",
    },
  ],
  wondez: [
    {
      name: "Fairy Wonde",
      type: "wonde",
      price: "$9.99",
      level: "Novice",
      rating: "2",
      releaseDate: "1986",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/wondez/fairy_wonde.jpg",
    },
    {
      name: "Generic Wonde",
      type: "wonde",
      price: "$29.99",
      level: "Intermediate",
      rating: "3",
      releaseDate: "1988",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/wondez/generic_wand.jpg",
    },
    {
      name: "Stick from a tree",
      type: "wonde",
      price: "34.99",
      level: "Intermediate",
      rating: "4",
      releaseDate: "0",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/wondez/normal_wooden_stick.jpg",
    },
    {
      name: "Yet Another Stick",
      type: "wonde",
      price: "$119.99",
      level: "Novice",
      rating: "4",
      releaseDate: "2014",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/wondez/tree_stuff.jpg",
    },
    {
      name: "John Halo from Fortnite Signiture Series Wonde",
      type: "wonde",
      price: "$1199.99",
      level: "Expert",
      rating: "5",
      releaseDate: "2003",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/wondez/john_halo_from_fortnite.jpg",
    },
    {
      name: "The Terminator",
      type: "wonde",
      price: "$99.99",
      level: "Advanced",
      rating: "5",
      releaseDate: "2011",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/wondez/The_Terminator.jpg",
    },
    {
      name: "Wrong Franchise",
      type: "wonde",
      price: "2499.99",
      level: "Expert",
      rating: "5",
      releaseDate: "2983",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/wondez/wrong_franchise.jpg",
    },
    {
      name: "Glock",
      type: "wonde",
      price: "$449.99",
      level: "Intermediate",
      rating: "4",
      releaseDate: "1776",
      description:
        "Lorem Ipsum something or whatever, this is made to be filler text to test the description box",
      image: "../images/wondez/glock.jpg",
    },
  ],
};
